### ISSUE TITLE
Counterexample

### ISSUE THREAD

**Issue by benjaminbartsch** [neeraj8us/isomorphism#1]
If two graphs are isomophic, then your algorithm always computes the same signature.
BUT the opposite is not true.
If two graphs are not isomorphic the signature may be equal.

```
NODE-PERMUTATIONS = 720
NODES = 6, EDGES = 7, GROUPS = 18
COUNTEREAXAMPLE FOUND!
GRAPH 1
[0, 0, 0, 1, 0, 1]
[0, 0, 1, 1, 0, 1]
[0, 1, 0, 0, 1, 0]
[1, 1, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 1]
[1, 1, 0, 0, 1, 0]
GRAPH 2
[0, 0, 0, 1, 0, 1]
[0, 0, 1, 1, 1, 0]
[0, 1, 0, 0, 1, 0]
[1, 1, 0, 0, 0, 1]
[0, 1, 1, 0, 0, 0]
[1, 0, 0, 1, 0, 0]
```

If you draw them, one can see, that the first graph has no circles with three nodes (triangles), but the secons graph has.

**Comment by neerajmw** [comment]
Yes, it fails when it is possible to split the graph into two parts and these two parts are the exact mirror images of each other. There may be other cases when it does not work.
  I am trying an approach where we break this symmetry by adding a node to the vertices that have the same signature in the two graphs. I am exploring if the new graphs( with the add number of vertices) are isomorphic then the original graphs are isomorphic. otherwise not. In the attached image,  as you showed, the algorithm will conclude them as isomorphic. But the graphs c and d will not be concluded as non-isomorphic. All we have done is added a single edge between a new node and a node of the corresponding graphs that have the same signature according to the algorithm.

    I am yet to find a connected graph with the odd number of nodes and the above algorithm does not work
<img width="684" alt="Screenshot 2022-05-12 at 11 47 36 AM" src="https://user-images.githubusercontent.com/85823856/168004489-337bba27-b532-4a1d-9b3e-e895295886bd.png">
.

**Comment by benjaminbartsch** [comment]
NODE-PERMUTATIONS = 5040
NODES = 7, EDGES = 8, GROUPS = 66
COUNTEREAXAMPLE FOUND!
GRAPH 1
[0, 1, 0, 0, 0, 0, 1]
[1, 0, 1, 0, 0, 0, 0]
[0, 1, 0, 0, 1, 1, 0]
[0, 0, 0, 0, 1, 0, 1]
[0, 0, 1, 1, 0, 0, 0]
[0, 0, 1, 0, 0, 0, 1]
[1, 0, 0, 1, 0, 1, 0]
GRAPH 2
[0, 1, 0, 1, 0, 1, 0]
[1, 0, 0, 0, 1, 0, 0]
[0, 0, 0, 0, 1, 0, 1]
[1, 0, 0, 0, 0, 1, 0]
[0, 1, 1, 0, 0, 0, 1]
[1, 0, 0, 1, 0, 0, 0]
[0, 0, 1, 0, 1, 0, 0]

**Comment by benjaminbartsch** [comment]
![ExampleN7](https://user-images.githubusercontent.com/83505980/168039950-86685034-8bf5-4bb1-92b2-9d7041d11693.png)

**Comment by neeraj8us** [comment]
Can you please confirm if this is fixed in latest code?

**Comment by benjaminbartsch** [comment]
IsoMorphicGraphSignatureDP

This import does not make sense. It cannot be resolved.
import sun.font.TrueTypeFont;

**Comment by benjaminbartsch** [comment]
The first counterexample I've found is for nodes=6, and edges=7.

`
GRAPH 1
[0, 0, 0, 1, 0, 1]
[0, 0, 1, 1, 0, 1]
[0, 1, 0, 0, 1, 0]
[1, 1, 0, 0, 0, 0]
[0, 0, 1, 0, 0, 1]
[1, 1, 0, 0, 1, 0]
GRAPH 2
[0, 0, 0, 1, 0, 1]
[0, 0, 1, 1, 1, 0]
[0, 1, 0, 0, 1, 0]
[1, 1, 0, 0, 0, 1]
[0, 1, 1, 0, 0, 0]
[1, 0, 0, 1, 0, 0]

`

**Comment by benjaminbartsch** [comment]
![grafik](https://user-images.githubusercontent.com/83505980/172813389-691eb67b-4bf4-4c1b-9ccd-197b2aa8b20c.png)

**Comment by neeraj8us** [comment]
Try IsoMorphicGraphSignatureSelfDP.java, this contains the new algorithm

**Comment by neeraj8us** [comment]
Check out the latest code and run the following command to verify that issue has been fixed for the above graphs. Files ./graphs/issue1_1_graph.txt and ./graphs/issue1_2_graph.txt contains the above two graphs in adjacency list.

git clone git@github.com:neeraj8us/isomorphism.git
cd isomorphism
./gradlew build
java -cp ./build/libs/untitled-1.0-SNAPSHOT.jar **com.neer.IsomorphismCheck** graphs/graph1.txt graphs/graph2.txt
